version: '2'
services:
  mysql-container:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DATABASE=app_db
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
